#!/usr/bin/zsh
MAX_BRIGHTNESS=`cat /sys/class/backlight/intel_backlight/max_brightness`
BRIGHTNESS=`cat /sys/class/backlight/intel_backlight/brightness`
PERCENTAGE=`echo "2k 100 $BRIGHTNESS $MAX_BRIGHTNESS /*p" | dc`
echo "${PERCENTAGE:0:2}%"
