# zmodload zsh/zprof
# # Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
unsetopt beep
# # End of lines configured by zsh-newuser-install
# # The following lines were added by compinstall
# zstyle :compinstall filename '/home/poorpy/.zshrc'

autoload -Uz compinit
compinit
autoload -U +X bashcompinit && bashcompinit

# # End of lines added by compinstall

#source /usr/share/nvm/init-nvm.sh
source ~/.antigen-src/antigen.zsh
source ~/.aliases
source ~/.exports

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
antigen bundle systemd
antigen bundle rust
antigen bundle ripgrep
antigen bundle pip
antigen bundle poetry
antigen bundle fzf
antigen bundle golang
antigen theme minimal

antigen apply

# fpath+=~/.zfunc

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" || "$SSH_AUTH_SOCK" = "$XDG_RUNTIME_DIR/ssh-agent.socket" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

export PATH="$HOME/.poetry/bin:$PATH"
