# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/poorpy/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# export EDITOR='nvim'
# export READER='zathura'
# (cat ~/.cache/wal/sequences &)
# source ~/.cache/wal/colors-tty.sh

# alias grep='grep --color=auto'
# alias ls='ls --color=auto'
# alias ll='ls -l'
# alias vimrc='cd /home/poorpy/.config/nvim/; nvim init.vim; cd -; '
# alias :q='exit'
# alias cls='clear; ls'
# alias cll='clear; ll'
# alias gdb='gdb -quiet'


# export PATH=$PATH:/home/poorpy/.bin:/home/poorpy/.cargo/bin
# export PATH=$PATH:/home/poorpy/.local/bin
# export PATH=$PATH:/home/poorpy/.emacs.d/bin


SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

source ~/.antigen-src/antigen.zsh
source ~/.aliases
source ~/.exports
antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle cargo
antigen bundle git
antigen bundle systemd
antigen bundle rust
antigen bundle ripgrep
antigen bundle pip
antigen bundle src
antigen theme minimal

antigen apply

fpath+=~/.zfunc

# export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
# export CC=/usr/bin/clang
# export CXX=/usr/bin/clang++

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.cabal/bin:$PATH"
# export PATH="$HOME:/.local/bin:$PATH"
